function_config:
  runtime: python312
  timeout_seconds: 60
  memory_mb: 128
  cpu: 1
  instance_count: 5000

trigger_config:
  region: us-central1
  event_type: google.cloud.storage.object.v1.finalized
  bucket: oms-order-creation

