-- Most demanded product and total revenue generated

-- Business logic:
-- 1. The goal is to find the most demanded product, defined as the one with the highest total number of units sold.

-- 2. To compute the total revenue generated by the product, we must multiply `quantity * total_price` at the row level.
--    This is because `total_price` represents the price of a single unit, not the full line item.

-- 3. Simply summing `total_price` would underestimate revenue if customers bought multiple units in a single order.

-- 4. The resulting revenue is a key business metric that could be used to measure the impact of marketing campaigns,
--    or prioritize inventory and promotions based on financial performance.

-- Query efficiency and BigQuery best practices:
-- - Grouping by `product_id` (an integer + clustered) is faster and cheaper than grouping by strings (e.g. product_name).
-- - Aggregating `quantity` and computing `SUM(quantity * total_price)` is done in a single pass over clustered data.

SELECT
    product_id,
    SUM(quantity) AS total_quantity,
    SUM(quantity * total_price) AS total_revenue

FROM
    `zubale.zubale.orders`

GROUP BY
    product_id

ORDER BY
    total_quantity DESC

LIMIT 1

-- results:
-- the product 5 is the most demanded product
-- but not the one that generated more profit for the company
-- that one is the 11, the n5 it's ranked in the top4